# Generated by Django 5.0 on 2024-01-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singhdarbarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
