# Generated by Django 5.0 on 2024-01-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singhdarbarapp', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
