# Generated by Django 5.0 on 2024-01-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhdarbarapp', '0004_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sweet', 'Sweets'), ('dhaba', 'Dhaba')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('khoya', 'Khoya'), ('bengoli', 'Bengoli'), ('laddu', 'Laddu'), ('chaat', 'Chaat'), ('snaks', 'Snaks'), ('kaju', 'Kaju'), ('chips', 'Chips'), ('mathi', 'Mathi')], max_length=255),
        ),
    ]
