# Generated by Django 5.0 on 2024-01-11 20:22

import singhdarbarapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhdarbarapp', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=singhdarbarapp.models.image_upload_path),
        ),
    ]
