# Generated by Django 5.0 on 2024-01-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singhdarbarapp', '0009_alter_product_description_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
